### ISSUE TITLE
Would you like to add your game music to the soundtrack?

### ISSUE THREAD

**Issue by lopis** [anttihaavikko/js13k-2024#1]
I loved the tune of your game and was wondering if you'd like to add it to this years [soundtrack album](https://js13k.bandcamp.com/album/triskaidekaphobia-js13k-2024)?

**Comment by anttihaavikko** [comment]
Ah crap, saw this when you first posted it but was busy at the time and then completely forgot it. I could still do it I guess, what would I need to do?

**Comment by lopis** [comment]
No worries! If you can just somehow extract of record some length of the music of the game, that would be lovely. I used `MediaRecorder` to record my music using [this script](https://github.com/lopis/thirteen-terrible-stunts/blob/recorder/music-recorder.html) but you could also just record the PC audio.

**Comment by anttihaavikko** [comment]
Oh yeah I've already got mp3 of it here
[coup-ahoo.mp3.zip](https://github.com/user-attachments/files/17330457/coup-ahoo.mp3.zip)

**Comment by lopis** [comment]
Sorry for the delay. It's been added. If you want, you can also make a 1400 x 1400 pixel cover art image.

**Comment by anttihaavikko** [comment]
Cool cool. You can use this...
![coup-ahoo-bc-cover](https://github.com/user-attachments/assets/13acf927-05aa-47b7-af3e-bdd8059bcb41)
